version: '3'

services:
       jenkins:
              image: jenkins/jenkins:lts
              privileged: true
              ports:
                     - 8080:8080
                     - 50000:50000
              container_name: jenkins-master
              volumes:
                     - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
                     - /var/run/docker.sock:/var/run/docker.sock
       backend-calculator:
              build: ./backend/
              ports:
                     - "8080"
              restart: always
       frontend-calculator:
              build: ./frontend/src/main/simplecalculator-ng
              links:
                     - "backend-calculator"
              depends_on:
                     - "backend-calculator"
              ports:
                     - "80:80"
